language: rust
rust:
  - stable
  - 1.40.0
  
os:
  - linux
  - windows
  - osx

before_install:
  - rustup component add clippy rustfmt

install:
  - cargo clippy -- -Wclippy::all
  - cargo fmt -- --check
  - cargo test
  - cargo doc --all-features
